### ISSUE TITLE
Code border is padded on some posts

### ISSUE THREAD

**Issue by philipmat** [philipmat/philipmat.github.io#1]
See this screenshot:

![screen shot 2016-07-08 at 2 43 28 pm](https://cloud.githubusercontent.com/assets/709928/16699568/7b9925b0-451a-11e6-8d42-0bf2a1265cc1.png)

**Comment by philipmat** [comment]
The culprit is the old `{% highlight %}` tag which wraps the  code `<pre>`  in a `<figure class="highlight">` block to which the browsers add their own styling:

```css
figure {
    display: block;
    -webkit-margin-before: 1em;
    -webkit-margin-after: 1em;
    -webkit-margin-start: 40px;
    -webkit-margin-end: 40px;
}
```
